name: Deploy movix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Injetar API Key no environment
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Build do Angular
        run: npm run build -- --configuration=production

      - name: Enviar arquivos para a VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: "/var/www/movix"

      - name: Reiniciar Caddy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: caddy reload --config /etc/caddy/Caddyfile
